apiVersion: v1
kind: Pod
metadata:
  name: pod-portal-de-noticias
  labels:
    app: portal-noticias
spec:
  containers:
    - name: portal-de-noticias
      image: aluracursos/portal-noticias:1
      ports:
        - containerPort: 80
      envFrom: # Busca os valores da variável de ambiente de um configMap
        - configMapRef: # Referencia do configMap
            name: portal-configmap # Usa o nome do configMap como refêrencia