apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: portal-noticias-replicaset
spec:
  template: # Modelo para criação de Pod, daqui pra baixo é um arquivo de criação de Pod comum
    metadata:
      name: portal-noticias
      labels:
        app: portal
    spec:
      containers:
        - name: portal-noticias-container
          image: aluracursos/portal-noticias:1
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: portal-configmap
  replicas: 3 # Número de replicas do Pod modelo (o total de pods será 3 mesmo)
  selector: # Indica o modelo que deve ser seguido
    matchLabels:
      app: portal # Aponto para a label do Pod do template feito acima.
