apiVersion: v1
kind: Service
metadata:
  name: svc-portal-de-noticias
spec:
  type: NodePort
  selector:
    app: portal
  ports:
    - port: 80 # Porta interna
      #targetPort: 80 # Porta que o Pod ta ouvindo.
      nodePort: 30000 # Porta externa, a que de fato vamos usar para acessar a aplicação (deve ser entre 30000 - 32767)