apiVersion: v1
kind: ConfigMap
metadata:
  name: db-configmap
data:
  # Chave: Valor | A chave é a variável solicitada no ambiente | O valor é valor que queremos dar à variável
  MYSQL_ROOT_PASSWORD: q1w2e3r4
  MYSQL_DATABASE: empresa
  MYSQL_PASSWORD: q1w2e3r4