apiVersion: apps/v1
kind: Deployment
metadata:
  name: sistema-de-noticias-deployment
spec:
  template:
    metadata:
      name: pod-sistema-de-noticias
      labels:
        app: sistema-noticias
    spec:
      containers:
        - name: sistema-de-noticias-container
          image: aluracursos/sistema-noticias:1
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: sistema-configmap
  replicas: 1
  selector:
    matchLabels:
      app: sistema-noticias